### PR TITLE
Fix readme to tell all necessary steps on how to setup.

### PR DESCRIPTION
**Pull request by ls42**
Hi,

I just noticed that your readme does not quite contain all steps to set up your VIM config.

Have a nice day :)

### CODE REVIEW

**Comment by jfrazelle** [comment]
thanks I also have a script for this :) but thanks! I like putting the real command so this is perfect

**Comment by ls42** [comment]
Wow, you're fast :) I didn't even have the time to update the PR with this change: 

-* [vim-airline](https://github.com/bling/vim-airline) - Lean status/tabline
+* [vim-lightline](https://github.com/bling/vim-airline) - light and configurable statusline/tabline

... I noticed that you changed that, too.

**Comment by ls42** [comment]
Well, pasting a `diff -u` of a markdown file was not a good idea...

Anyway, thanks!

**Comment by jfrazelle** [comment]
oh maybe i should be using the other one?

**Comment by jfrazelle** [comment]
added a script :) https://github.com/jfrazelle/.vim/commit/08d4b3aec472209bc006930af43c93bb97103afe

**Comment by ls42** [comment]
Your .gitmodule says that you're not using vim-airline anymore, but https://github.com/itchyny/lightline.vim.git

So for correctness you should change it, yeah :)

**Comment by ls42** [comment]
> added a script :) 08d4b3a

Alrighty! I'm out

**Pull request merged**
